version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: SiteFabricio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT_HOST:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=SiteFabricio
      - DB_PORT=5432
      - DB_HOST=db
      - EMAIL_USER=seu_email@gmail.com
      - EMAIL_PASS=sua_senha
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT_HOST:-5000}:5000"
    command: sh -c "npx wait-port db:5432 && sleep 10 && node server.js"

  frontend:
    build:
      context: .
    ports:
      - "${FRONTEND_PORT_HOST:-3000}:3000"
    depends_on:
      - backend

  flyway:
    image: flyway/flyway:10
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/SiteFabricio -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql

volumes:
  db_data: